planning/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login_user, name='login'),
    path('home/', views.home_prof, name='home'),


    path('plaquetteProf/', views.IndexPlaquetteProf, name='plaquetteProf'),

    path('deconnexion/',views.deconnexion, name='deconnexion' ),
    path('listeEleveProf/',views.liste_eleve_prof, name='listeEleveProf' ),



    path('plaquettesecretaire/', views.plaquettesecretaire, name='plaquettesecretaire'),
    path('EditEleve/<int:id>/', views.editEleve, name='EditEleve'),
    path('ajout/', views.ajout, name='ajout'),
    path('liste_eleve/', views.liste_eleve, name='liste_eleve'),
    path('delE/<int:id>/', views.delEleve, name='dele'),
    path('index/', views.Index, name='index'),
    path('index_eleve/', views.Index_eleve, name='index_eleve'),
    path('add_planning/', views.addPlanning, name='add'),
    path('del/<int:id>/', views.delPlanning, name='del'),
    path('edit/<int:id>/', views.editPlanning, name='edit'),
    path('notification/<int:id>/', views.notifications, name='notification'),
    path('addPlaquette/', views.AjoutPlaquette, name='addPlaquette'),
    path('addPlaquette1/', views.AjoutPlaquette1, name='addPlaquette1'),
    path('addPlaquette2/', views.AjoutPlaquette2, name='addPlaquette2'),
    path('addPlaquette3/', views.AjoutPlaquette3, name='addPlaquette3'),
    path('addPlaquette4/', views.AjoutPlaquette4, name='addPlaquette4'),
    path('editPlaquette/<int:id>/', views.editPlaquette, name='editPlaquette'),
    path('editPlaquette1/<int:id>/', views.editPlaquette1, name='editPlaquette1'),
    path('editPlaquette2/<int:id>/', views.editPlaquette2, name='editPlaquette2'),
    path('editPlaquette3/<int:id>/', views.editPlaquette3, name='editPlaquette3'),
    path('editPlaquette4/<int:id>/', views.editPlaquette4, name='editPlaquette4'),
    path('DelPlaquette/<int:id>/', views.DelPlaquette, name='delplaquette'),
    path('DelPlaquette1/<int:id>/', views.DelPlaquette1, name='delplaquette1'),
    path('DelPlaquette2/<int:id>/', views.DelPlaquette2, name='delplaquette2'),
    path('DelPlaquette3/<int:id>/', views.DelPlaquette3, name='delplaquette3'),
    path('DelPlaquette4/<int:id>/', views.DelPlaquette4, name='delplaquette4'),
    path('secretaire/', views.secretaire, name='secretaire'),
    path('cahiersecretaire/', views.cahiersecretaire, name='cahiersecretaire'),
    path('contactsecretaire/', views.contactsecretaire, name='contactsecretaire'),
    path('classe/', views.classe, name='classe'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = " Administrateur"
admin.site.site_title = "Planning"
admin.site.index_title = "Welcome to Planning Project Admin"

myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import  User
# Create your models here.

class Secretaire(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Liaison 0netoOne vers le model User
    nom=models.CharField(max_length=50)
    prenom=models.CharField(max_length=50)
    mail=models.CharField(max_length=100)
    telephone=models.CharField(max_length=20)
    photo = models.ImageField(upload_to="Images/")
    class Meta :
        verbose_name_plural = "Secretaire"


    def __str__(self):
        return " {0}".format(self.user.username)


class Classe(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Liaison 0netoOne vers le model User
    nom_classe=models.CharField(max_length=50)
    photo = models.ImageField(upload_to="Images/")
    class Meta:
        verbose_name_plural = "Classe"
        ordering = ['nom_classe']

    def __str__(self):
        return "{0}".format(self.user.username)


class Eleve(models.Model):
    nom_eleve=models.CharField(max_length=50)
    prenom_eleve=models.CharField(max_length=50)
    id_classe=models.ForeignKey('Classe', on_delete=models.CASCADE)
    email = models.EmailField(blank=True)

    class Meta:
        verbose_name_plural = "Eleve"
        ordering = ['nom_eleve']


    def __str__(self):
        return self.prenom_eleve

class Responsable_Eleve(Eleve):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Liaison 0netoOne vers le model User

    class Meta:
        verbose_name_plural = "Responsable de classe"
        ordering = ['prenom_eleve']

    def __str__(self):
        return " {0}".format(self.user.username)

class CahierTexte(models.Model):
    heure_cours=models.CharField(max_length=50)
    date=models.DateField()
    contenu=models.TextField()
    id_classe=models.ForeignKey('Classe', on_delete=models.CASCADE)
    id_cours=models.ForeignKey('Cours', on_delete=models.CASCADE)


    class Meta:
        verbose_name_plural = "Cahier de texte"
        ordering = ['date']

    def __str__(self):
        return self.contenu


class Prof(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Liaison 0netoOne vers le model User
    nom_prof=models.CharField(max_length=50)
    prenom_prof=models.CharField(max_length=50)
    mail_prof=models.CharField(max_length=50)
    photo = models.ImageField(upload_to="Images/")
    classe=models.ManyToManyField(Classe)

    class Meta :
        verbose_name_plural = "Professeur"

    def __str__(self):
        return "{0}".format(self.user.username)

class Responsable_Prof(Prof):
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta :
        verbose_name_plural = "Responsable pédagogique"

    def __str__(self):
        return self.prenom_prof


class Cours(models.Model):
    nom_cours=models.CharField(max_length=50)
    duree=models.CharField(max_length=50)
    date=models.DateField()
    id_prof=models.ForeignKey('Prof', on_delete=models.CASCADE)
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta :
        verbose_name_plural = "Cours"

    def __str__(self):
        return self.nom_cours

class Notification(models.Model):
    date=models.DateTimeField(default=timezone.now, verbose_name='date d envoi')
    contenu=models.TextField()
    id_prof_emmet= models.IntegerField()
    id_prof_recep = models.ForeignKey('Prof', on_delete=models.CASCADE)

    class Meta :
        verbose_name_plural = "Notifications"

    def __str__(self):
        return self.contenu

class Enseigner(models.Model):
    id_cours=models.ManyToManyField(Cours)
    id_prof=models.ForeignKey('Prof', on_delete=models.CASCADE)

    class Meta :
        verbose_name_plural = "Enseigner"

    def __str__(self):
        return str (self.id_prof)



class PresAbs(models.Model):
    nom_eleve=models.CharField(max_length=400)
    id_cours=models.ForeignKey('Cours', on_delete=models.CASCADE)
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)
    date = models.DateField()
    heure = models.CharField(max_length=10)

    class Meta :
        verbose_name_plural = "Absences"
        ordering = ['date']
    def __str__(self):
        return self.nom_eleve

class Planning(models.Model):
    heure = models.CharField(max_length=7, null=True)
    moduleLundi = models.CharField(max_length=30, blank=True)
    moduleMardi = models.CharField(max_length=30, blank=True)
    moduleMercredi = models.CharField(max_length=30, blank=True)
    moduleJeudi = models.CharField(max_length=30, blank=True)
    moduleVendredi = models.CharField(max_length=30, blank=True)
    moduleSamedi = models.CharField(max_length=30, blank=True)
    id_prof=models.ForeignKey('Responsable_Prof', on_delete=models.CASCADE)
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Planning"


    def __str__(self):
        return self.heure


class Plaquette(models.Model):
    ue = models.CharField(max_length=40, blank=True)
    ec = models.CharField(max_length=30)
    cm = models.CharField(max_length=3)
    tpd = models.CharField(max_length=3)
    ttal = models.CharField(max_length=3)
    tpe = models.CharField(max_length=3)
    ects = models.CharField(max_length=3)
    total_Ects = models.CharField(max_length=3, blank=True)
    coefs = models.CharField( max_length=2, blank=True)
    coefs_details = models.IntegerField()
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)


    class Meta:
        verbose_name = "Plaquette"

    def __str__(self):
        return self.ec

class Plaquette1(models.Model):
    ue = models.CharField(max_length=40, blank=True)
    ec = models.CharField(max_length=30)
    cm = models.CharField(max_length=3)
    tpd = models.CharField(max_length=3)
    ttal = models.CharField(max_length=3)
    tpe = models.CharField(max_length=3)
    ects = models.CharField(max_length=3)
    total_Ects = models.CharField(max_length=3, blank=True)
    coefs = models.CharField( max_length=2, blank=True)
    coefs_details = models.IntegerField()
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Plaquette1"

    def __str__(self):
        return self.ec

class Plaquette2(models.Model):
    ue = models.CharField(max_length=40, blank=True)
    ec = models.CharField(max_length=30)
    cm = models.IntegerField()
    tpd = models.IntegerField()
    ttal = models.IntegerField()
    tpe = models.IntegerField()
    ects = models.IntegerField()
    total_Ects = models.CharField(max_length=3, blank=True)
    coefs = models.CharField( max_length=2, blank=True)
    coefs_details = models.IntegerField()
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Plaquette2"

    def __str__(self):
        return self.ec

class Plaquette3(models.Model):
    ue = models.CharField(max_length=40, blank=True)
    ec = models.CharField(max_length=30)
    cm = models.IntegerField()
    tpd = models.IntegerField()
    ttal = models.IntegerField()
    tpe = models.IntegerField()
    ects = models.IntegerField()
    total_Ects = models.CharField(max_length=3, blank=True)
    coefs = models.CharField( max_length=2, blank=True)
    coefs_details = models.IntegerField()
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Plaquette3"

    def __str__(self):
        return self.ec

class Plaquette4(models.Model):
    ue = models.CharField(max_length=40, blank=True)
    ec = models.CharField(max_length=30)
    cm = models.IntegerField()
    tpd = models.IntegerField()
    ttal = models.IntegerField()
    tpe = models.IntegerField()
    ects = models.IntegerField()
    total_Ects = models.CharField(max_length=3, blank=True)
    coefs = models.CharField( max_length=2, blank=True)
    coefs_details = models.IntegerField()
    id_classe = models.ForeignKey('Classe', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Plaquette4"

    def __str__(self):
        return self.ec

myapp/forms.py
from django import forms
from .models import *

###Login user
class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

class EleveForm(forms.ModelForm):
    class Meta:
        model = Eleve
        fields = '__all__'

class PlanningForm(forms.ModelForm):
    class Meta:
        model = Planning
        fields = '__all__'

class NotificationForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = '__all__'

class CahierTexteForm(forms.ModelForm):
    class Meta:
        model = CahierTexte
        fields = '__all__'

class PresAbsenceForm(forms.ModelForm):
    nom_eleve = forms.CharField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    class Meta:
        model = PresAbs
        fields = '__all__'

class PlaquetteForm(forms.ModelForm):
    class Meta:
        model = Plaquette
        fields = '__all__'

class Plaquette1Form(forms.ModelForm):
    class Meta:
        model = Plaquette1
        fields = '__all__'

class Plaquette2Form(forms.ModelForm):
    class Meta:
        model = Plaquette2
        fields = '__all__'

class Plaquette3Form(forms.ModelForm):
    class Meta:
        model = Plaquette3
        fields = '__all__'

class Plaquette4Form(forms.ModelForm):
    class Meta:
        model = Plaquette4
        fields = '__all__'

myapp/templates/level2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Planning</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{% static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="index.html">Dashboard</a></li>
                      <li><a href="index2.html">Dashboard2</a></li>
                      <li><a href="index3.html">Dashboard3</a></li>
                    </ul>
                  </li>
                
                 
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              
             
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                      <img src="{% static 'images/img.jpg' %}" alt="">John Doe
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                      
                    
                      <a class="dropdown-item"  href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </div>
                  </li>
  
                  
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
              <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                  <div class="x_title">

                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>

                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>


                  <div class="x_content">
                      <div class="row">
                          <div class="col-sm-12">
                            <div class="card-box table-responsive">

                    <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                      <thead>
                        <tr>
                          <th>Heure</th>
                          <th>Lundi</th>
                          <th>Mardi</th>
                          <th>Mercredi</th>
                          <th>Jeudi</th>
                          <th>Vendredi</th>
                          <th>Samedi </th>
                          <th>Dimanche</th>
                        </tr>
                      </thead>


                      <tbody>
                        <tr>
                          <td>Tiger Nixon</td>
                          <td>System Architect</td>
                          <td>Edinburgh</td>
                          <td>61</td>
                          <td>2011/04/25</td>
                          <td>$320,800</td>
                          <td>2011/04/25</td>
                          <td>$320,800</td>
                        </tr>
                        <tr>
                          <td>Garrett Winters</td>
                          <td>Accountant</td>
                          <td>Tokyo</td>
                          <td>63</td>
                          <td>2011/07/25</td>
                          <td>$170,750</td>
                          <td>2011/04/25</td>
                          <td>$320,800</td>
                        </tr>

                        <tr>
                          <td>Donna Snider</td>
                          <td>Customer Support</td>
                          <td>New York</td>
                          <td>27</td>
                          <td>2011/01/25</td>
                          <td>$112,000</td>
                          <td>2011/04/25</td>
                          <td>$320,800</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  </div>
              </div>
            </div>


                </div>
              </div>
                
                <!-- ECRIRE ICI -->

                <!-- ECRIRE ICI -->



              </div>
            </div>
          </div>
        </div>

        <!-- /page content -->





        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Planning 2019 by Fallilou Fall and Mohamet Tall
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
   <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    
    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
  </body>
</html>

myapp/templates/notification.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Planning</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                {% for i in prof %}
               <img src="{{ i.photo.url }}" class="img-circle profile_img">
                {% endfor %}
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ user.username }}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        {% for i in der %}
                        {% if z == i.prenom_prof %}
                      <li><a href="{% url 'index' %}">CRUD planning-plaquette</a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                  </li>
                
                 
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              
             
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'deconnexion' %}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                        {% for i in prof %}
                      <img src="{{ i.photo.url }}" alt="">
                        {% endfor %}
                       {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                      
                    
                      <a class="dropdown-item"  href="{% url 'deconnexion' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </div>
                  </li>
  
                  
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
              <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 ">


                <link href="{% static 'blog/notif.css' %}" rel="stylesheet" type="text/css">
               <form action="{% url 'notification' id %}" method="post">
            {% csrf_token %}
            <input type="hidden"  name="date" value= '{{ a|date:"Y-m-d h:i:s"  }}' required id="id_date">
            <input type="hidden" name="id_prof_emmet" value= '{{ c }}'>
            <div class="container">
                <div class="messaging">
                    <div class="inbox_people">
                        <div class="headind_srch">
                            <div class="recent_heading">
                                <h4>Envoyés</h4>
                            </div>
                            <div class="form-group">
                                <select name="id_prof_recep">
                                    <optgroup label="Professeurs">
                                        {% for i in res %}
                                            <option value="{{ i.id }}">{{ i.prenom_prof }} {{ i.nom_prof }}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                        </div>

                        <div class="inbox_chat">
                            {% for i in notif1 %}
                                <div class="chat_list">
                                    <div class="chat_people">
                                        {% for i in prof %}
                                            <div class="chat_img"> <img src="{{ i.photo.url }}" style="border-radius:50%;"  alt="sunil"> </div>
                                        {% endfor %}
                                        <div class="chat_ib">
                                        {% for j in res %}
                                            {% if j.id == i.id_prof_emmet %}
                                                <h5>{{ j.prenom_prof }} {{ j.nom_prof }} <span class="chat_date">{{ i.date }}</span></h5>
                                                    <p>{{ i.contenu }}</p>
                                            {% endif %}
                                        {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="panel-footer" >
                            <div class="input-group">
                                <input  name="contenu" class="form-control input-sm" placeholder="Type your message here..." style="height:30px;"/>
                                    <span class="input-group-btn" style="width:50px; height:30px;" >
                                        <button type="submit" value="submit" class="btn btn-success btn-sm" style="margin-left:0;">Send</button>
                                    </span>
                            </div>

                        </div>
                    </div>

                    <div class="messaging">

                        <div class="inbox_people rak">
                            <div class="headind_srch">
                                <div class="recent_heading">
                                    <h4>Reçus</h4>
                                </div>

                            </div>
                            <div class="inbox_chat">
                                {% for i in notif %}
                                    <div class="chat_list active_chat">
                                        <div class="chat_people">
                                            {% for j in res %}
                                                    {% if j.id == i.id_prof_emmet %}
                                            <div class="chat_img"> <img src="{{ j.photo.url }}" style="border-radius:50%;" alt="sunil"> </div>
                                                <div class="chat_ib">
                                                         <h5>{{ j.prenom_prof }} {{ j.nom_prof }} <span class="chat_date">{{ i.date }}</span></h5>
                                                         <p>{{ i.contenu }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                                </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                        </div>

                    </div>

                </div>

             </div>

        </form>


              </div>

                <!-- ECRIRE ICI -->

                <!-- ECRIRE ICI -->



              </div>
            </div>
          </div>
        </div>

        <!-- /page content -->





        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Planning 2019 by Fallilou Fall and Mohamet Tall
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
   <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    
    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.min.js' %}"></script>
  </body>
</html>